### ISSUE TITLE
Errors while compiling.

### ISSUE THREAD

**Issue by ssCherry** [Mempler/Sora#8]
Using .NET Core 2.2 (Also tried .NET Core 3 but same problem)
![изображение](https://user-images.githubusercontent.com/42537021/59873499-d50f9a80-93a4-11e9-8e88-b3421af33389.png)

**Comment by Mempler** [comment]
Install the LATEST Dotnet core 3.0 Preview aka
Dotnet Core preview6
https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-preview6-windows-x86-installer

**Comment by ssCherry** [comment]
i installed but it doesnt appear here
![изображение](https://user-images.githubusercontent.com/42537021/59943630-66e1db00-946b-11e9-878d-ec698d021ccf.png)

**Comment by Mempler** [comment]
You also require VS2019 Preview to use dotnet core 3 preview6

or use vscode instead and run `dotnet run Sora -c Debug`

**Comment by ssCherry** [comment]
yeah i use VS2019, okay i try 2nd way.

**Comment by ssCherry** [comment]
Thanks, second way work.
